module.exports={
  assetsDir:"static/home",
  devServer:{
    proxy:{
      '/api':{
        target:'http://127.0.0.5',
      },
      '/uploads':{
      	target:'http://127.0.0.5',
      }
    }
  }
}